version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: 1
      #FLASK_ENV: development
    depends_on:
      - db
  db:
    image: postgres:14.2
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=pass_culture
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_ROOT_PASSWORD=root
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
#$ docker exec -t postgresql pg_dumpall -c -U baeldung > dump.sql
#$ cat dump.sql | docker exec -i postgresql psql -U baeldung
